<?php


/*
 * Form to choose what are the fields to encrypt
 */

 function crypto_config() {
   $form = array();

   $user_entity = entity_metadata_wrapper('user', NULL, array('bundle' => 'user'));
   $user_info = $user_entity->getPropertyInfo();
   $field_list = array();
   foreach ($user_info as $key_field_user => $value_field_user){
    if(isset($value_field_user['type'])){
      if($value_field_user['type'] == 'text'){
        $field_list[$key_field_user] = t(''.$value_field_user['label'].'');
      }
    }
   }
   $form['user_field_list'] = array(
     '#title' => t('Liste de champs à chiffrer'),
     '#type' => 'checkboxes',
     '#description' => t('Choisir les champs à chiffrer'),
     '#options' => $field_list,
     '#default_value' => variable_get('user_field_list'),
   );
   return system_settings_form($form);
 }

function crypto_config_fields_menu(){
  $items = array();
  $items['admin/config/system/crypto_fields'] = array(
    'title' => 'Configure fields to encrypt on user',
    'description' => 'Select what fields are going to be crypt or not',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crypto_config'),
    'access arguments' => array('administer crypto fields'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function crypto_config_fields_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'crypto_config'){
    $form['#submit'][] = '_crypto_config_submit';
  }
}

function _crypto_config_submit($form, &$form_state){
  //On récupère la longueur max des champs cochés
  foreach($form_state['values']['user_field_list'] as $field_name => $value_field) {
    if($value_field != '0'){
      $result = db_query("SELECT data FROM field_config WHERE field_name = '".$field_name."'");
      $config = $result->fetchField();
      $config_array = unserialize($config);
      $length_field = $config_array['settings']['max_length'];
      $new_length = $length_field *8;
      //Prepare request for update length
      $field_table = 'field_data_' . $field_name;
      $field_revision_table = 'field_revision_' . $field_name;
      $field_column = $field_name . '_value';
      // Alter value field length in fields table
      db_query("ALTER TABLE ".$field_table." ALTER ".$field_column." TYPE VARCHAR( ".$new_length." )");
      // Alter value field length in fields revision table
      db_query("ALTER TABLE ".$field_revision_table." ALTER ".$field_column." TYPE VARCHAR( ".$new_length." )");
    }
  }
}
